### ISSUE TITLE
Bug when user wants to save time slots in Moodle version 3.2 with theme Boost

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#30] opened 2017-04-12 08:13 UTC
Hi,

as we are testing your plugin with Moodle 3.2 and Boost, I'm encountering a bug.

1. Create a new organizer or use an existing one
2. Go to the page /mod/organizer/slots_add.php and  do the settings to choose slots that should be created. Make sure that you type something in the mandatory field "Location".
3. Click "Review time slots".
4. Check the time slots and see that the field "Location" is filled and grayed out. If everything is correct, then click on "Create time slots".
5. See that the time slots are not created, and the user keeps staying on this page requiring the user to enter a location although this field was filled and even grayed ou (because it's a mandatory field and the system would have never let the user continue to the next step if it would be left empty).

Then, it's not always possible to create the time slots after entering the location and clicking "Create time slots" again, because the browser thinks I would leave the site and asks if I want to stay on this browser site, because if I leave the form it will not be processed and the data is gone.
However it does not always recognise that I entered a location again. Most of the time, it's working if I try it a second time. But that's kind of frustrating to repeat all steps again.

With theme Clean, I cannot reproduce this bug. There, the creating of the time slots works as expected in my tests. So I think this is really related to the new theme base Boost.

Best regards,

**Comment by bluetom** [comment] 2017-04-12 08:52
Hi Kathrin,
thanks for your message!
Our tester found the same bug recently but we had'nt thought the boost theme to be the cause of this bug before now. So thanks for the hint, I'll have a look to it asap...
Best regards

**Comment by Kathrin84** [comment] 2017-04-13 07:13
Hi Tom, thanks in advance! :)

**Comment by Goldenflamer** [comment] 2017-05-08 15:27
I have the same bug, any updates?

**Comment by kaspot** [comment] 2017-08-08 06:30
Hi, this bug should be fixed in the newest Organizer version — pls let us know if you encounter any further problems.
Cheers Kasia

**Closed by kaspot** 2017-08-08 06:30 UTC

**Comment by Kathrin84** [comment] 2017-09-01 10:16
Hi Kasia,
thanks for the information and the solution. Unfortunately is integrated in your 3.3 version that requires Moodle 3.3. We are not on Moodle 3.3. yet, so we would have to provide your plugin with this bug to our users. My question is if you could provide a short patch that just fixes this 3.2 Boost issue or update your plugin's 3.2 version? This would be really great.
Best, Kathrin

**Comment by kaspot** [comment] 2017-09-12 12:08
Dear Kathrin, 
I'll check with our developer if there is any way we can help you. Updating to 3.3 is not an option for you?
Cheers Kasia

**Comment by Kathrin84** [comment] 2017-09-12 12:56
Hi Kasia,
we're about to launch 3.2 the next few weeks and did not have the chance to even have a glance at Moodle 3.3 - so updating to 3.3 won't be possible for the next time for our production system...

**Comment by bluetom** [comment] 2017-09-12 13:19
Hi Kathrin,
so I see the problem clearer: with this bug you can't put the organizer into production...I'll have a look at it and let you know what is possible...
Cheers Thomas

**Comment by Kathrin84** [comment] 2017-09-12 13:24
Hi Thomas,
thanks for your efforts with this issue. A solution (patch or a bug fixed version for Moodle 3.2) is very much appreciated. 👍

**Comment by bluetom** [comment] 2017-09-12 15:30
[view_action_form_add.php.zip](https://github.com/academic-moodle-cooperation/moodle-mod_organizer/files/1296436/view_action_form_add.php.zip)
This page is taken from the organizer version MOODLE_32_STABLE (2017013101).
The fix is located at line #341 and #342.
Hope it helps...(as it does in my local environment with moodle 3.2 and moodle 3.3)

**Comment by Kathrin84** [comment] 2017-09-13 06:58
Hi Thomas,
I've tested your tipp right now (just replaced the whole PHP file) and in my first test everything worked fine. :) So I think this should solve the problem. Until we can upgrade to Moodle 3.3, we will keep this hack in our system to be able to continue providing your plugin in our production environment.
Thanks @all for your effort! 👍 
Best, Kathrin

**Comment by mkemmerling** [comment] 2017-09-19 13:08
The fix is now included in v3.2.2.

**Comment by abias** [comment] 2017-09-19 13:23
Thanks, Markus, for including this fix in an official version! This saves us from backporting it to 3.2.
