### ISSUE TITLE
Feature Request: Add possibility to allow a student or group to register for more than one time slot

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#22] opened 2016-06-20 08:43 UTC
Hi together,

we've got the feature request, if it's possible to allow students to register for multiple time slots. At the moment, a teacher can allow a student to reappoint another slot. Then he will be deleted (version 3.0.0) from the old slot and signed in into the new one.

For some use cases it's not comfortable or impossible to create multiple organizers to workaround this requested behavior.

So, I think the best would be to make a setting that sets the slot amounts a student can register for. E.g. if this setting would be 3, then a student can (or have to?) register for 3 slots within the same organizer.

If you like the idea of this feature, would you also accept a pull request? So maybe we can implement or order a development for this feature.

Cheers, Kathrin

**Comment by mkemmerling** [comment] 2016-06-20 10:08
Hi Kathrin,

if I understand it right this issue extends #17 by allowing registration for more than time slot not only in group mode?

For some reason I received your last comment on #17 per mail, but it doesn't show up in GitHub itself. Strange. So I answer your question "And if we would provide a pull request, would you accept it?" here.

In general, we try to implement feature requests from the community if we consider them useful and if our limited resources allow us to do so. Of course feature requests of AMC members (as well as bug fixes) have priority over community requests. If we consider a feature request to be generally useful a pull request is very much appreciated. It will certainly raise the chance for the feature to be implemented for the next release, but we can not give you any guarantee.

For the organizer plugin there is currently still a lot of work to be done for the Moodle 3.1 version planned to be released in September. Unfortunately, the chance that your feature request will make it into the 3.1 version is therefore rather low.

Cheers,
Markus

**Comment by Kathrin84** [comment] 2016-06-20 10:15
Hi Markus,
> if I understand it right this issue extends #17 by allowing registration for more than time slot not only in > group mode?

First I thought so and extended issue #17. However I think this one is separate, so I undid my changes and opened this issue.

#17  is about allowing more than 1 group to a single slot.
This one is to allow single students or group to register for more than 1 slot. 
I think those are seperate issues.

Cheers, Kathrin

**Comment by mkemmerling** [comment] 2016-06-21 09:54
I missed the difference, thanks for clarifying. I will create a new feature request in our development backlog.

**Comment by Kathrin84** [comment] 2016-09-30 08:02
Hi Markus,
just for our internal ticket tracking purposes:
Is it planned or realistic that this feature could be implemented for your Moodle 3.2 version of the plugin?
Cheers, Kathrin

**Comment by kaspot** [comment] 2017-02-20 09:24
Hi Kathrin, 
unfortunately the feature didn't make it into our 3.2 version of the plugin. Although it still is in our Backlog list.
Cheers Kat

**Comment by Kathrin84** [comment] 2018-01-16 12:30
I just wanted to give you feedback that this feature is quite highly required at our university and there are several support tickets in which users say that they cannot register for a new slot, when they already took one.
Of course I tell them that the teacher has to enable this for their specific slot, however, a setting for enabling re-registrations for a whole organizer instance would be really nice and useful from our point of view.

**Comment by abias** [comment] 2018-08-23 21:36
Hi Thomas, hi Kathrin,

> Yes, I think this should be sufficient. A possibility to define an unlimited amount of slot appointments would be helpful, too. Especially in the first scenario it is not estimate-able how often a student would want to use the consultation hour. So an open limit would fit this case best.

I would like to add one important thing:
* The teacher needs to be able to control how often a student / group can book a slot as described by you, Tom, and as confirmed by you, Kathrin, with real life examples.
* The teacher might also want to control how many slots can be booked _concurrently_ by a student / group. This should be a separate setting with default value = 1. The value 1 means that a student can only book one slot at a time - he will not be able to book another slot before the first booked slot is done. A higher or unlimited value means that a student / group will be allowed to book several or unlimited slots at a time.

Separating the feature into two new settings would let teachers prevent that students / groups book all the nice slots during the whole lecture term (as an extreme example), but will still let them book another slot after the first booked slot is done without any interaction of the teacher (which is the original spirit of this issue).

Cheers,
Alex

**Comment by bluetom** [comment] 2018-08-24 10:46
Ok, I thank Kathrin and Alex for the clarifications! I will mengle them with my ideas for this feature and then update my estimation of developer hours, which I will send to Andreas right away...
Cheers,
Thomas

**Comment by magarHSNR** [comment] 2018-12-03 15:36
Is there any news concerning the topic? We get similar request for enrolling for multiple time slots.
Thanks and regards,
Mark

**Comment by goggo24** [comment] 2019-05-02 14:09
Hey, because the feature is important for us too, we have just begun working on "multiple registrations":
a teacher config a minimun and maximum number of slots to which a student/group can register. Our goal is to release this new feature with v.3.7.x of the organizer plugin. Hopefully our plan works out :)

**Comment by abias** [comment] 2019-05-03 11:30
Thank you, Eva, this is great news!
If we can help you in any way with beta-testing, please don't hesitate to get in touch with me.

Cheers,
Alex

**Comment by goggo24** [comment] 2019-06-30 11:00
Status quo for this "big" new feature: unfortunately, it won't be finished for v.3.7.x. As part of the implemetation, some unexpected questions or behaviors have emerged, we have to deal with first. At the moment we stopped working on this feature and put our development ressources into a publishable v.3.7.0. and fix some bugs. Afterwards we will work on with this feature and try to code it in a "clean" way.

**Comment by sehomer** [comment] 2020-11-19 14:43
Hello,

we are also interested in this feature, are there any news on this?

Best regards
Sebastian

**Comment by Bambuspony** [comment] 2021-04-20 21:41
Hi,
same here, also interested that a student may book more than one slot in the same planner. Any news are welcome. Any help needed?
Greetings, Martin.

**Comment by krendlV** [comment] 2021-10-06 07:38
Hello, 
We would also need the function that more than one timeslot can be booked.
Is this feature still planned?

All the best
Valentin

**Comment by bluetom** [comment] 2023-08-21 13:16
The current organizer versions 3.11.7 and 4.2 are providing this feature.

**Closed by bluetom** 2023-08-21 13:16 UTC
Labels: enhancement
