### ISSUE TITLE
Missing functionality in table registration status with version 3.0.0

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_organizer#23] opened 2016-06-21 11:40 UTC
Hi toghether,

it's me again. A user told us that a behavior in the table registration status in version 3.0.0 is different to the prior versions.

In the versions < 3.0.0 it's possible to grade or regrade a user in this table:
![registration_status_29](https://cloud.githubusercontent.com/assets/4711883/16228107/4bcf489a-37b5-11e6-9474-2c246119e2b8.png)

In 3.0.0 those strings are displayed, however the buttons are disabled:
![registration_status_300](https://cloud.githubusercontent.com/assets/4711883/16228122/6053677e-37b5-11e6-9ce4-b9c4570717e5.png)

I would like to ask if this is intended behavior and if so, what is the reason for this change.
If not, this might be a bug.

Cheers, Kathrin

**Comment by mkemmerling** [comment] 2016-06-21 15:37
Hi Kathrin,

thanks for reporting. Doesn't look like intended behaviour to me, but I can not answer your question definitely. Anyway, I created a bug ticket in our backlog.

Cheers,
Markus

**Comment by bluetom** [comment] 2016-06-22 05:04
Hi Kathrin,

I can only find one criteria for the disabling of those buttons in the code: It happens if the capability "mod/organizer:evalslots" is missing for the current user(-role) in this context. Could you check this?
(There were no changes in this area since Version 2.8 at least...)

Thanks and Cheers, Thomas

**Comment by Kathrin84** [comment] 2016-06-22 05:21
Hi Markus and Thomas,

thanks for your reply. As I'm Moodle admin, I think I should automatically have all capabilities of new plugins, however those buttons are also disabled to me. And I checked the capability for our teachers (one of them reported the bug) and they definitely have this capability.

Cheers, Kathrin

**Comment by bluetom** [comment] 2016-06-22 05:46
Hi Kathrin,
here is part of the code:

	$evalenabled = has_capability('mod/organizer:evalslots', $context, null, true);
.
.

        case ORGANIZER_APP_STATUS_ATTENDED:
            $button = new stdClass();
            $button->text = get_string("btn_reeval", 'organizer');
            $button->url = $evalurl;
            $button->disabled = !$evalenabled;
            $buttons[] = $button;
            break;

        case ORGANIZER_APP_STATUS_ATTENDED_REAPP:
            $button = new stdClass();
            $button->text = get_string("btn_reeval", 'organizer');
            $button->url = $evalurl;
            $button->disabled = !$evalenabled;
            $buttons[] = $button;
            break;

        case ORGANIZER_APP_STATUS_PENDING:
            $button = new stdClass();
            $button->text = get_string("btn_eval_short", 'organizer');
            $button->url = $evalurl;
            $button->disabled = !$evalenabled;
            $buttons[] = $button;
            break;
etc.
We can't reproduce this problem at our site.
If you have definitely checked the capability in the given context we have to do further investigations...

Cheers, Thomas

**Comment by bluetom** [comment] 2016-06-22 07:20
Dear Kathrin,

could you please tell me the exact version of your installation? (2016-01-28 (8)?)

Thanks, tom

**Comment by Kathrin84** [comment] 2016-06-23 08:31
Hi Tom,

we're working on our productive System with Moodle 3.0.3+ (Build: 20160415) and Organizer Version 3.0.0 (2016041800)
For testing purposes I installed a older version of Organizer (2015-12-17 (1)
2015121702).

Cheers, Kathrin

**Comment by mkemmerling** [comment] 2016-06-25 03:59
The bug has been fixed in v3.0.1 (2016050401). Please update.

**Closed by mkemmerling** 2016-06-25 03:59 UTC
